<div class="row" style="justify-content: space-between;">
    <h1>
        <?= $this->titulo; ?>
    </h1>
    <button class="btn btn-primary mt-2 mb-2" data-toggle="modal" data-target="#modalInsert">
        <i class="fas fa-plus mr-1"></i>
        Agregar
    </button>
</div>

<div class="row" style="justify-content: end; width: 100%; margin-left: 15px;">
    <button class="btn btn-primary mt-2 mb-2">
        <i class="fas fa-print mr-1"></i>
        Imprimir
    </button>

</div>

<table class="table table-bordered table-hover" >
    <thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Cantidad</th>
            <th>Precio</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->listaProductos as $producto): ?>
        <tr>
            <td> <?php echo $producto->getId() ?> </td>
            <td> <?php echo $producto->getNombre() ?> </td>
            <td> <?php echo $producto->getDescripcion() ?> </td>
            <td> <?php echo $producto->getCantidad() ?> </td>
            <td> <?php echo $producto->getPrecio() ?> </td>
            <td>
            <button class="btn btn-btn-outline-primary" data-toggle="modal" data-target="#modalEditandDelete">
                <i class="fas fa-edit mr-1"></i>
                Ver producto
            </button>
                <!-- <a href=" <?php echo $this->basePath()?>/inventario/ver/<?php echo $producto->getId() ?> ">Ver producto</a> -->
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<!-- Modal de registro -->
<div class="modal fade" id="modalInsert" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Understood</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal de edicion y eliminación -->
<div class="modal fade" id="modalEditandDelete" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Understood</button>
      </div>
    </div>
  </div>
</div>

