

<div class="container-fluid mt-5">
    <div class="col">
        <p style="font-size: 25px; font-weight: 700; margin-bottom: 0;">Iniciar Sesión</p>
        <p style="font-size: 15px; margin-top: 0;">Ingresa tus datos para entrar a tu stock</p>
    </div>

    <div class="col mt-5">
    <form>
        <div class="form-group">
            <label for="exampleInputEmail1">Correo electronico</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <div class="row" style="justify-content: space-between;">
                <label for="exampleInputPassword1">Contraseña</label>
                <a href="#">¿Olvidaste tu contraseña?</a>
            </div>
            <input type="password" class="form-control" id="exampleInputPassword1">
        </div>
        <button type="submit" class="btn btn-primary btn-block">Iniciar Sesión</button>
    </form>
    <hr>
    <div class="col mt-3" >
        <p>¿No tienes una cuenta en stock?</p>
        <button class="btn btn-secundary btn-block">Unirme ahora</button>
    </div>
    </div>
</div>